on: [push]

jobs:
  acetao_job:
    runs-on: ubuntu-latest
    name: Test parsing acetao.ini
    steps:
    - name: Checkout OpenDDS
      uses: actions/checkout@v4
      with:
        path: OpenDDS
        submodules: true
    - name: Parse step
      id: acetaoversion
      uses: OpenDDS/acetao-ini-parser@v0.4.0
      with:
        section: 'ace6tao2'
    - name: Output some stuff
      run: echo "desc ${{ steps.acetaoversion.outputs.desc }} version ${{ steps.acetaoversion.outputs.version }}"
